version: '3.8'
services:
  superkassa-server:
    build: .
    depends_on:
      - sk_example_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sk_example_db:5432/sk_example_db

  sk_example_db:
    image: postgres:14-alpine
    container_name: sk_example_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sk_example_db
      - POSTGRES_USER=sk_example_user
      - POSTGRES_PASSWORD=password
